### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ndzamboni** [ndzamboni/css-cheatsheet#1]
- [ ] Add original ReadMe from class
- [ ] Be sure to put credits in (didn't make this)
- [ ] Maybe look to create a JavaScript version of this
- [ ] Add more CSS blocks
